# Address and port for clients (core API module)
clients:
    address: "*"
    port: 9658
# Address and port for workers
workers:
    address: "*"
    port: 9657
    max_liveness: 4
    ping_interval: 1000
# Frontend address which will be used for notifying on certain events
notifier:
    address: "https://your.recodex.domain/api/v1/broker-reports"
    port: 443
    username: "rebroker"                  # This must match the configuration of core API module
    password: "generateSecretPasswdHere"  # see 'broker' > 'auth'
monitor:
    address: "127.0.0.1"
    port: 7894
logger:
    file: "/var/log/recodex/broker"  # w/o suffix - actual names will be broker.log, broker.1.log, ...
    level: "debug"  # level of logging
    max-size: 1048576  # 1 MB; max size of file before log rotation
    rotations: 3  # number of rotations kept
queue_manager: "single"  # name of the manager that handles job dispatching among queues (single is the default)
